apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 3000          # Port for the service
      targetPort: 3000    # Port on the container
      nodePort: 30007     # Port on your host machine (must be between 30000–32767)